# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_raw/initial_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InitialWindow(object):
    def setupUi(self, InitialWindow):
        InitialWindow.setObjectName("InitialWindow")
        InitialWindow.setWindowModality(QtCore.Qt.WindowModal)
        InitialWindow.resize(500, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InitialWindow.sizePolicy().hasHeightForWidth())
        InitialWindow.setSizePolicy(sizePolicy)
        InitialWindow.setMinimumSize(QtCore.QSize(500, 400))
        InitialWindow.setMaximumSize(QtCore.QSize(864, 16666))
        font = QtGui.QFont()
        font.setFamily("Serif")
        InitialWindow.setFont(font)
        InitialWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        InitialWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(InitialWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 400))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 115151))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.funcsInitialLayout = QtWidgets.QVBoxLayout()
        self.funcsInitialLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.funcsInitialLayout.setSpacing(6)
        self.funcsInitialLayout.setObjectName("funcsInitialLayout")
        self.funcName = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.funcName.sizePolicy().hasHeightForWidth())
        self.funcName.setSizePolicy(sizePolicy)
        self.funcName.setMaximumSize(QtCore.QSize(16777215, 50))
        self.funcName.setObjectName("funcName")
        self.funcsInitialLayout.addWidget(self.funcName)
        self.openFileLayout = QtWidgets.QHBoxLayout()
        self.openFileLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.openFileLayout.setObjectName("openFileLayout")
        self.displayPlanFile = QtWidgets.QLineEdit(self.centralwidget)
        self.displayPlanFile.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayPlanFile.sizePolicy().hasHeightForWidth())
        self.displayPlanFile.setSizePolicy(sizePolicy)
        self.displayPlanFile.setMinimumSize(QtCore.QSize(0, 0))
        self.displayPlanFile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.displayPlanFile.setMouseTracking(False)
        self.displayPlanFile.setReadOnly(True)
        self.displayPlanFile.setObjectName("displayPlanFile")
        self.openFileLayout.addWidget(self.displayPlanFile)
        self.openPlanFile = QtWidgets.QPushButton(self.centralwidget)
        self.openPlanFile.setMinimumSize(QtCore.QSize(0, 0))
        self.openPlanFile.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.openPlanFile.setBaseSize(QtCore.QSize(0, 0))
        self.openPlanFile.setObjectName("openPlanFile")
        self.openFileLayout.addWidget(self.openPlanFile)
        self.funcsInitialLayout.addLayout(self.openFileLayout)
        self.verticalLayout.addLayout(self.funcsInitialLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.displayProbFile = QtWidgets.QLineEdit(self.centralwidget)
        self.displayProbFile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.displayProbFile.setObjectName("displayProbFile")
        self.horizontalLayout.addWidget(self.displayProbFile)
        self.openProbFile = QtWidgets.QPushButton(self.centralwidget)
        self.openProbFile.setObjectName("openProbFile")
        self.horizontalLayout.addWidget(self.openProbFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.displayTrafficFile = QtWidgets.QLineEdit(self.centralwidget)
        self.displayTrafficFile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.displayTrafficFile.setObjectName("displayTrafficFile")
        self.horizontalLayout_3.addWidget(self.displayTrafficFile)
        self.openTrafFile = QtWidgets.QPushButton(self.centralwidget)
        self.openTrafFile.setObjectName("openTrafFile")
        self.horizontalLayout_3.addWidget(self.openTrafFile)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.autoModeCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoModeCheckBox.sizePolicy().hasHeightForWidth())
        self.autoModeCheckBox.setSizePolicy(sizePolicy)
        self.autoModeCheckBox.setObjectName("autoModeCheckBox")
        self.verticalLayout.addWidget(self.autoModeCheckBox)
        self.handModeHorLayout = QtWidgets.QHBoxLayout()
        self.handModeHorLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.handModeHorLayout.setContentsMargins(-1, -1, -1, 0)
        self.handModeHorLayout.setSpacing(5)
        self.handModeHorLayout.setObjectName("handModeHorLayout")
        self.bettaInitialLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bettaInitialLabel.sizePolicy().hasHeightForWidth())
        self.bettaInitialLabel.setSizePolicy(sizePolicy)
        self.bettaInitialLabel.setObjectName("bettaInitialLabel")
        self.handModeHorLayout.addWidget(self.bettaInitialLabel)
        self.bettaInitialField = QtWidgets.QLineEdit(self.centralwidget)
        self.bettaInitialField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bettaInitialField.setObjectName("bettaInitialField")
        self.handModeHorLayout.addWidget(self.bettaInitialField)
        self.xInitialLabel = QtWidgets.QLabel(self.centralwidget)
        self.xInitialLabel.setObjectName("xInitialLabel")
        self.handModeHorLayout.addWidget(self.xInitialLabel)
        self.xInitialField = QtWidgets.QLineEdit(self.centralwidget)
        self.xInitialField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xInitialField.setObjectName("xInitialField")
        self.handModeHorLayout.addWidget(self.xInitialField)
        self.yInitialLabel = QtWidgets.QLabel(self.centralwidget)
        self.yInitialLabel.setObjectName("yInitialLabel")
        self.handModeHorLayout.addWidget(self.yInitialLabel)
        self.yInitialField = QtWidgets.QLineEdit(self.centralwidget)
        self.yInitialField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yInitialField.setObjectName("yInitialField")
        self.handModeHorLayout.addWidget(self.yInitialField)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.handModeHorLayout.addWidget(self.label_3)
        self.tInitialField = QtWidgets.QLineEdit(self.centralwidget)
        self.tInitialField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tInitialField.setObjectName("tInitialField")
        self.handModeHorLayout.addWidget(self.tInitialField)
        self.verticalLayout.addLayout(self.handModeHorLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.betta0InitialField = QtWidgets.QLineEdit(self.centralwidget)
        self.betta0InitialField.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.betta0InitialField.sizePolicy().hasHeightForWidth())
        self.betta0InitialField.setSizePolicy(sizePolicy)
        self.betta0InitialField.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.betta0InitialField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.betta0InitialField.setObjectName("betta0InitialField")
        self.horizontalLayout_2.addWidget(self.betta0InitialField)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.betta1InitialField = QtWidgets.QLineEdit(self.centralwidget)
        self.betta1InitialField.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.betta1InitialField.sizePolicy().hasHeightForWidth())
        self.betta1InitialField.setSizePolicy(sizePolicy)
        self.betta1InitialField.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.betta1InitialField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.betta1InitialField.setObjectName("betta1InitialField")
        self.horizontalLayout_2.addWidget(self.betta1InitialField)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.okDialog = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.okDialog.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okDialog.sizePolicy().hasHeightForWidth())
        self.okDialog.setSizePolicy(sizePolicy)
        self.okDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.okDialog.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.okDialog.setCenterButtons(False)
        self.okDialog.setObjectName("okDialog")
        self.verticalLayout.addWidget(self.okDialog)
        InitialWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InitialWindow)
        QtCore.QMetaObject.connectSlotsByName(InitialWindow)

    def retranslateUi(self, InitialWindow):
        _translate = QtCore.QCoreApplication.translate
        InitialWindow.setWindowTitle(_translate("InitialWindow", "Thresholds initial"))
        self.funcName.setText(_translate("InitialWindow", "План показов S(t)"))
        self.openPlanFile.setText(_translate("InitialWindow", "Открыть"))
        self.label.setText(_translate("InitialWindow", "Распределение аудитории p(w)"))
        self.openProbFile.setText(_translate("InitialWindow", "Открыть"))
        self.label_2.setText(_translate("InitialWindow", "Функция траффика z(t)"))
        self.openTrafFile.setText(_translate("InitialWindow", "Открыть"))
        self.autoModeCheckBox.setText(_translate("InitialWindow", "Автоматический режим"))
        self.bettaInitialLabel.setText(_translate("InitialWindow", "b"))
        self.bettaInitialField.setText(_translate("InitialWindow", "0.01"))
        self.xInitialLabel.setText(_translate("InitialWindow", "X0"))
        self.xInitialField.setText(_translate("InitialWindow", "0.0"))
        self.yInitialLabel.setText(_translate("InitialWindow", "Y0"))
        self.yInitialField.setText(_translate("InitialWindow", "0.0"))
        self.label_3.setText(_translate("InitialWindow", "T"))
        self.tInitialField.setText(_translate("InitialWindow", "1.0"))
        self.label_4.setText(_translate("InitialWindow", "betta0"))
        self.betta0InitialField.setText(_translate("InitialWindow", "0.0"))
        self.label_5.setText(_translate("InitialWindow", "betta1"))
        self.betta1InitialField.setText(_translate("InitialWindow", "1.0"))

